version: '3.7'
services:
  mongo:
    image: mongo:4.4.0
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db:/data/db # 挂载数据目录
      - ./mongo/log:/var/log/mongodb  # 挂载日志目录
      - ./mongo/config:/etc/mongo  # 挂载配置目录

  redis:
    container_name: qiusuo-redis
    image: redis:5.0.3
    ports:
      - '6379:6379'
    command: ["redis-server"]

networks:
  default:
    external:
      name: dev-qiusuo-cluster